service_name: abcdef
exporter_config:
  endpoint: localhost:4317
  insecure: yes
  headers: null
  timeout: null
provider_config:
  sampler: null
  shutdown_on_exit: yes
custom_config:
  any_key: null